getHierarchicalClientsByCategory = obj => {
    sql='select a.client_id,a.category_id,Y.id,Y.level,c.picwa from categories_clients a left outer join '
    sql+='(select id,level from ( '
    sql+='select a.id , "level1" level from qiscus.messagecategories a '
    sql+='left outer join qiscus.messagecategories b on b.parent_id=a.id '
    sql+='left outer join qiscus.messagecategories c on c.parent_id=b.id '
    sql+='left outer join qiscus.messagecategories d on d.parent_id=c.id '
    sql+='left outer join qiscus.messagecategories e on e.parent_id=d.id '
    sql+='where a.id='+obj.id+' '
    sql+='union '
    sql+='select b.id, "level2" level from qiscus.messagecategories a '
    sql+='left outer join qiscus.messagecategories b on b.parent_id=a.id '
    sql+='left outer join qiscus.messagecategories c on c.parent_id=b.id '
    sql+='left outer join qiscus.messagecategories d on d.parent_id=c.id '
    sql+='left outer join qiscus.messagecategories e on e.parent_id=d.id '
    sql+='where a.id=345'
    sql+='union '
    sql+='select c.id, "level3" level from qiscus.messagecategories a '
    sql+='left outer join qiscus.messagecategories b on b.parent_id=a.id '
    sql+='left outer join qiscus.messagecategories c on c.parent_id=b.id '
    sql+='left outer join qiscus.messagecategories d on d.parent_id=c.id '
    sql+='left outer join qiscus.messagecategories e on e.parent_id=d.id '
    sql+='where a.id='+obj.id+' '
    sql+='union '
    sql+='select d.id, "level4" level from qiscus.messagecategories a '
    sql+='left outer join qiscus.messagecategories b on b.parent_id=a.id '
    sql+='left outer join qiscus.messagecategories c on c.parent_id=b.id '
    sql+='left outer join qiscus.messagecategories d on d.parent_id=c.id '
    sql+='left outer join qiscus.messagecategories e on e.parent_id=d.id '
    sql+='where a.id='+obj.id+' '
    sql+='union '
    sql+='select e.id, "level5" level from qiscus.messagecategories a '
    sql+='left outer join qiscus.messagecategories b on b.parent_id=a.id '
    sql+='left outer join qiscus.messagecategories c on c.parent_id=b.id '
    sql+='left outer join qiscus.messagecategories d on d.parent_id=c.id '
    sql+='left outer join qiscus.messagecategories e on e.parent_id=d.id '
    sql+='where a.id='+obj.id+' '
    sql+=') X where id is not null)Y on Y.id=a.category_id '
    sql+='left outer join clients c on c.id=a.client_id '
    sql+='where Y.id is not null and c.picwa  is not null '
    return sql
}
module.exports = {
    getHierarchicalClientsByCategory:getHierarchicalClientsByCategory
}